### ISSUE TITLE
Better handling of s3 relation

### ISSUE THREAD

**Issue by kian99** [canonical/postgresql-operator#180]
This seems to be a duplicate of https://github.com/canonical/postgresql-operator/issues/129 so could be closed since that issue is already resolved. 

## Steps to reproduce

1. `juju deploy postgresql` (revision 288 was used)
2. `juju deploy s3-integrator`
3. `juju run-action s3-integrator/leader sync-s3-credentials access-key=<access-key> secret-key=<secret-key> --wait`
4. `juju config s3-integrator <key>=<value>`
5. `juju relate s3-integrator postgresql`

At this point because of firewall rules, my postgres unit could not talk to my Radosgw server and it was pending for a while with the status saying `initialising stanza` until eventually the status changed to `Blocked` with a message `failed to initialize stanza`. 

After fixing the firewall rules I am unable to set up backups as I don't know how to get Postgres to retry the setup. Attempts to remove the s3-integrator relation and re-add it fail, as log messages state `couldn't initialize stanza due to a blocked status`. See below for all the logs.

Finally, trying  `juju run-action postgresql/0 list-backups --wait` caused an exception (logs also available below).

## Expected behavior
Expected that I can trigger Postgres to retry the connection to Swift storage somehow.

## Actual behavior
See above.

## Versions

Operating system: Ubuntu 22.04.2 LTS

Juju CLI: 2.9.42

Juju agent: 2.9.42

Charm revision: 288

LXD: N/A

## Log output
<details><summary>Failed to reach Radosgw</summary>
<p>

```
unit-ubuntu-advantage-0: 06:54:35 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-landscape-client-0: 06:55:18 INFO juju.worker.uniter.operation skipped "update-status" hook (missing)
unit-s3-integrator-0: 06:55:23 DEBUG unit.s3-integrator/0.juju-log Operator Framework 2.3.0 up and running.
unit-s3-integrator-0: 06:55:23 DEBUG unit.s3-integrator/0.juju-log Emitting Juju event update_status.
unit-s3-integrator-0: 06:55:23 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 06:55:55 DEBUG unit.s3-integrator/0.juju-log Operator Framework 2.3.0 up and running.
unit-s3-integrator-0: 06:55:55 DEBUG unit.s3-integrator/0.juju-log Emitting Juju event sync_s3_credentials_action.
unit-s3-integrator-0: 06:55:55 DEBUG unit.s3-integrator/0.juju-log Updated S3 connection info: {'access-key': 'redacted'}
unit-s3-integrator-0: 06:55:55 DEBUG unit.s3-integrator/0.juju-log Updated S3 connection info: {'secret-key': 'redacted'}
unit-s3-integrator-0: 06:55:56 DEBUG unit.s3-integrator/0.juju-log s3-integrator-peers:0: Operator Framework 2.3.0 up and running.
unit-s3-integrator-0: 06:55:56 DEBUG unit.s3-integrator/0.juju-log s3-integrator-peers:0: Emitting Juju event s3_integrator_peers_relation_changed.
unit-s3-integrator-0: 06:55:56 INFO unit.s3-integrator/0.juju-log s3-integrator-peers:0: Missing options: []
unit-postgresql-0: 06:55:57 DEBUG unit.postgresql/0.juju-log s3-parameters:6: Operator Framework 2.2.0 up and running.
unit-postgresql-0: 06:55:57 DEBUG unit.postgresql/0.juju-log s3-parameters:6: Emitting Juju event s3_parameters_relation_changed.
unit-postgresql-0: 06:55:57 DEBUG unit.postgresql/0.juju-log s3-parameters:6: Emitting custom event <CredentialsChangedEvent via PostgresqlOperatorCharm/S3Requirer[s3-parameters]/on/credentials_changed[6765]>.
unit-s3-integrator-0: 06:55:57 INFO juju.worker.uniter.operation ran "s3-integrator-peers-relation-changed" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 07:00:42 DEBUG unit.s3-integrator/0.juju-log Operator Framework 2.3.0 up and running.
unit-s3-integrator-0: 07:00:42 DEBUG unit.s3-integrator/0.juju-log Emitting Juju event update_status.
unit-s3-integrator-0: 07:00:44 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 07:03:59 ERROR unit.postgresql/0.juju-log s3-parameters:6: ERROR: [049]: timeout connecting to 'radosgw.ps5.canonical.com:443'

unit-postgresql-0: 07:04:06 INFO juju.worker.uniter.operation ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
unit-telegraf-0: 07:04:07 INFO unit.telegraf/0.juju-log Reactive main running for hook update-status
```

</p>
</details>

<details><summary>Remove and re-add relation</summary>
<p>

```
unit-data-integrator-0: 08:14:58 INFO juju.worker.uniter.operation ran "postgresql-relation-changed" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 08:18:22 INFO juju.worker.uniter.operation ran "s3-credentials-relation-departed" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 08:18:22 INFO juju.worker.uniter.operation ran "s3-parameters-relation-departed" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 08:18:24 INFO juju.worker.uniter.operation ran "s3-credentials-relation-broken" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 08:18:25 INFO juju.worker.uniter.operation ran "s3-parameters-relation-broken" hook (via hook dispatching script: dispatch)
unit-landscape-client-0: 08:18:36 INFO juju.worker.uniter.operation skipped "update-status" hook (missing)
unit-ubuntu-advantage-0: 08:18:39 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 08:18:54 INFO juju.worker.uniter.operation ran "s3-credentials-relation-created" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 08:18:55 INFO juju.worker.uniter.operation ran "s3-credentials-relation-joined" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 08:18:55 INFO juju.worker.uniter.operation ran "s3-parameters-relation-created" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 08:18:56 INFO juju.worker.uniter.operation ran "s3-credentials-relation-changed" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 08:18:58 INFO juju.worker.uniter.operation ran "s3-parameters-relation-joined" hook (via hook dispatching script: dispatch)
unit-s3-integrator-0: 08:18:59 INFO juju.worker.uniter.operation ran "s3-credentials-relation-changed" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 08:19:00 WARNING unit.postgresql/0.juju-log s3-parameters:13: couldn't initialize stanza due to a blocked status
unit-postgresql-0: 08:19:02 INFO juju.worker.uniter.operation ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
unit-postgresql-0: 08:19:04 WARNING unit.postgresql/0.juju-log s3-parameters:13: couldn't initialize stanza due to a blocked status
unit-postgresql-0: 08:19:11 INFO juju.worker.uniter.operation ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
```

</p>
</details>

<details><summary>Attempted to list backups</summary>
<p>

```
unit-telegraf-0: 08:19:50 INFO juju.worker.uniter.operation ran "update-status" hook (via explicit, bespoke hook script)
unit-postgresql-0: 08:21:16 ERROR unit.postgresql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1028, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/backups.py", line 434, in _on_list_backups_action
    formatted_list = self._generate_backup_list_output()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/backups.py", line 186, in _generate_backup_list_output
    backups = json.loads(output)[0]["backup"]
IndexError: list index out of range
```

</p>
</details>

**Comment by kian99** [comment]
Just an update on this. I upgrade the charm to channel `14/candidate` and revision `307`. The unit status has changed to an error but when I try `juju resolve postgresql/0` I get the following in `juju debug-log`

```
unit-postgresql-0: 09:44:14 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-telegraf-0: 09:44:15 INFO juju.worker.uniter.operation ran "update-status" hook (via explicit, bespoke hook script)
unit-postgresql-0: 09:44:19 ERROR unit.postgresql/0.juju-log s3-parameters:14: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1224, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/s3.py", line 694, in _on_relation_changed
    credentials = self.get_s3_connection_info()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/s3.py", line 711, in get_s3_connection_info
    relation = self.charm.model.get_relation(self.relation_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 249, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 769, in _get_unique
    raise TooManyRelatedAppsError(relation_name, num_related, 1)
ops.model.TooManyRelatedAppsError: Too many remote applications on s3-parameters (2 > 1)
unit-postgresql-0: 09:44:20 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-0: 09:44:20 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

Before this I did remove the relation with `juju remove-relation s3-integrator postgresql --force` and re-add it hoping that would fix it. I wonder if that might have caused the relation information to become inconsistent.
Next I tried scaling the cluster with `juju add-unit postgresql -n 1` and then new unit is stuck on `waiting to start Postgresql` while the leader is still in an error state.

Finally I decided to try `juju resolve postgresql/0 --no-retry` and Postgres moved on from failing that initial hook but is now stuck on the `database-peers-relation-changed` hook with the same error as before (logs below),
```
unit-postgresql-0: 09:47:40 ERROR unit.postgresql/0.juju-log database-peers:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1224, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 362, in _on_peer_relation_changed
    if not self.backup.start_stop_pgbackrest_service():
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/backups.py", line 800, in start_stop_pgbackrest_service
    are_backup_settings_ok, _ = self._are_backup_settings_ok()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/src/backups.py", line 79, in _are_backup_settings_ok
    if self.model.get_relation(self.relation_name) is None:
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 249, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 769, in _get_unique
    raise TooManyRelatedAppsError(relation_name, num_related, 1)
ops.model.TooManyRelatedAppsError: Too many remote applications on s3-parameters (2 > 1)
unit-postgresql-0: 09:47:41 ERROR juju.worker.uniter.operation hook "database-peers-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-0: 09:47:41 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```
Which all seems to come back to the inconsistent state of relation data. I would appreciate if there is any resolution to this issue.

**Comment by kian99** [comment]
<details><summary>And the output of `juju status --relations`</summary>
<p>

```
Model                        Controller    Cloud/Region           Version  SLA          Timestamp
prod-product-attribution-db  prodstack-is  prodstack5/prodstack5  2.9.42   unsupported  09:50:49Z

App               Version  Status  Scale  Charm             Channel        Rev  Exposed  Message
data-integrator            active      1  data-integrator   latest/stable   11  no       
landscape-client           active      2  landscape-client  stable          49  no       System successfully registered
postgresql        14.8     active      2  postgresql        14/stable      307  yes      
s3-integrator              active      1  s3-integrator     latest/stable   13  yes      
telegraf                   active      2  telegraf          stable          62  yes      Monitoring postgresql/0 (source version/commit d208a64)
ubuntu-advantage           active      2  ubuntu-advantage  stable          43  no       Attached (esm-apps,esm-infra,livepatch)

Unit                   Workload  Agent  Machine  Public address  Ports     Message
data-integrator/0*     active    idle   3        10.131.141.150            
postgresql/0*          error     idle   1        10.131.141.88   5432/tcp  hook failed: "database-peers-relation-changed"
  landscape-client/0*  active    idle            10.131.141.88             System successfully registered
  telegraf/0*          active    idle            10.131.141.88   9103/tcp  Monitoring postgresql/0 (source version/commit d208a64)
  ubuntu-advantage/0*  active    idle            10.131.141.88             Attached (esm-apps,esm-infra,livepatch)
postgresql/1           waiting   idle   4        10.131.141.177            waiting to start PostgreSQL
  landscape-client/1   active    idle            10.131.141.177            System successfully registered
  telegraf/1           active    idle            10.131.141.177  9103/tcp  Monitoring postgresql/1 (source version/commit d208a64)
  ubuntu-advantage/1   active    idle            10.131.141.177            Attached (esm-apps,esm-infra,livepatch)
s3-integrator/0*       active    idle   0        10.131.141.53             

Machine  State    Address         Inst id                               Series  AZ                   Message
0        started  10.131.141.53   a18308ff-cdb8-428f-85d8-c75a559803b7  jammy   availability-zone-3  ACTIVE
1        started  10.131.141.88   e2135e08-cb26-444a-a19b-56dcb4fa1003  jammy   availability-zone-1  ACTIVE
3        started  10.131.141.150  9ad1cba0-a7b5-420b-a166-f7459351cc3e  jammy   availability-zone-2  ACTIVE
4        started  10.131.141.177  0c3d7fb8-e4fb-4c4b-9065-d1c1e1e54cc8  jammy   availability-zone-2  ACTIVE

Offer       Application  Charm       Rev  Connected  Endpoint  Interface          Role
postgresql  postgresql   postgresql  307  1/1        database  postgresql_client  provider

Relation provider                      Requirer                               Interface              Type         Message
data-integrator:data-integrator-peers  data-integrator:data-integrator-peers  data-integrator-peers  peer         
postgresql:database                    data-integrator:postgresql             postgresql_client      regular      
postgresql:database-peers              postgresql:database-peers              postgresql_peers       peer         
postgresql:juju-info                   landscape-client:container             juju-info              subordinate  
postgresql:juju-info                   telegraf:juju-info                     juju-info              subordinate  
postgresql:juju-info                   ubuntu-advantage:juju-info             juju-info              subordinate  
postgresql:restart                     postgresql:restart                     rolling_op             peer         
s3-integrator:s3-integrator-peers      s3-integrator:s3-integrator-peers      s3-integrator-peers    peer
```


</p>
</details>

**Comment by kian99** [comment]
In the end I was able to get through this hook as well with another `juju resolve postgresql/0 --no-retry` and I removed the extra unit and Postgres is in an active state again (still with no backups configured).

I tried now to `juju relate s3-integrator postgresql` but still the issue persists.
```
unit-postgresql-0: 10:03:42 ERROR unit.postgresql/0.juju-log s3-parameters:16: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1224, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/s3.py", line 694, in _on_relation_changed
    credentials = self.get_s3_connection_info()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/data_platform_libs/v0/s3.py", line 711, in get_s3_connection_info
    relation = self.charm.model.get_relation(self.relation_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 249, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/model.py", line 769, in _get_unique
    raise TooManyRelatedAppsError(relation_name, num_related, 1)
ops.model.TooManyRelatedAppsError: Too many remote applications on s3-parameters (3 > 1)
unit-postgresql-0: 10:03:43 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-0: 10:03:43 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

I'll leave it at that. I have the model running in an environment in case more debug logs or tweaks are helpful.

**Comment by dragomirp** [comment]
Hi, was this model used before or was in a clean model? It looks to me that `s3` library believes it's related to multiple `s3-integrator` apps.

**Comment by kian99** [comment]
This was a clean model. I.e. everything described above was started from a clean environment. After the initial error there were attempts to `juju remove-relation s3-integrator postgresql --force` (sometimes with using `--force`) and then attempts to re-relate the two. It's possible doing these in somewhat quick succession (i.e. I waited less than a minute before `remove-relation` then `relate`) caused the state to become incorrect.

**Comment by dragomirp** [comment]
We'll most probably need to pass the relationship id in the `s3` lib as well, to make sure we can't hit this exception in the future. Thanks for reporting this.

**Comment by kian99** [comment]
@dragomirp Thank you!
