### ISSUE TITLE
PostgreSQL does not work with "legacy" proxy settings in juju

### ISSUE THREAD

**Issue by Barteus** [canonical/postgresql-operator#365]
## Steps to reproduce

1. Juju deploy bundle with landscape and postgres 14/stable in proxy environment (https://pastebin.canonical.com/p/6JnDN22Wz9/)
2. Wait for postgres to fail on install hook

I cannot use snap-proxy settings in juju model config, I have to use legacy proxy settings. Proxy is correctly configured because latest/stable works perfectly fine.

## Expected behavior
Postgres is installed properly

## Actual behavior

postgresql/1*          error        idle        8        172.29.151.31                   hook failed: "install"

## Versions

Operating system: Ubuntu 22.04.3 LTS

Juju CLI: 3.1.7-genericlinux-amd64

Juju agent: 3.1.7

Charm channel: 14/stable
Charm revision: 363

LXD: 5.0.3

## Log output

Juju debug log extract: 
```
unit-postgresql-0: 12:28:01 ERROR unit.postgresql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1497, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 765, in _on_install
    self._install_snap_packages(packages=SNAP_PACKAGES)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1274, in _install_snap_packages
    snap_package = snap_cache[snap_name]
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 829, in __getitem__
    self._snap_map[snap_name] = self._load_info(snap_name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 877, in _load_info
    info = self._snap_client.get_snap_information(name)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 785, in get_snap_information
    return self._request("GET", "find", {"name": name})[0]
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 742, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 763, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 679, in http_open
    return self.do_open(_UnixSocketConnection, req, socket_path=self.socket_path)
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out
unit-postgresql-0: 12:28:01 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-0: 12:28:01 INFO juju.worker.uniter awaiting error resolution for "install" hook
```

Full log: https://pastebin.canonical.com/p/7KwFQh5JXK/

**Comment by dragomirp** [comment]
Hi, @Barteus, I don't think the legacy charm uses snaps. The traceback indicates that the snap charm library cannot connect to the local snapd API. Can you try to do it manually from within the unit with something like `curl --unix-socket /run/snapd.socket http://localhost/v2/find?name=charmed-postgresql`? Is the snap CLI functional in the unit?

**Comment by Barteus** [comment]
I had to add the legacy juju proxy settings and snap-http-proxy and snap-https-proxy. It works this way.

**Comment by taurus-forever** [comment]
> I had to add the legacy juju proxy settings and snap-http-proxy and snap-https-proxy. It works this way.

Hi @Barteus , can you share the precise details to document to simplify the path for the followers here. Which options, which values, how ... (you can drop them here and we will move to the documentation). Tnx!
