### ISSUE TITLE
S3 Integration with Ceph Radosgw failing

### ISSUE THREAD

**Issue by gustavosr98** [canonical/postgresql-operator#471]
## Steps to reproduce
Follow these docs -> https://charmhub.io/postgresql-k8s/docs/h-configure-s3-radosgw

```
juju switch postgresql
juju deploy s3-integrator
juju run s3-integrator/leader sync-s3-credentials \
    access-key="$ACCESS_KEY" secret-key="$SECRET_KEY"

# Tried both ways
# A. Pre creating bucket
# B. Non pre created bucket
mc config host add ceph http://$CEPH_LEADER_IP:8080" $ACCESS_KEY $SECRET_KEY --api S3v4 --lookup path
mc mb ceph/postgresql
    
juju config s3-integrator \
    endpoint="http://$CEPH_LEADER_IP:8080" \
    bucket="postgresql" \
    path="/postgresql" \
    region="" \
    s3-api-version="" \
    s3-uri-style="path"
 
juju integrate s3-integrator postgresql-k8s
```

## Expected behavior
To not be on error state

## Actual behavior

```
postgresql-k8s/1*   error     idle   10.1.1.53            hook failed: "s3-parameters-relation-changed"
```

## Versions
Ceph: reef/stable
Juju CLI: 3.1.8
Juju agent: 3.1.8
Microk8s: 1.29/stable
Charms revision: 
- postgresql-k8s  14/stable  193
- s3-integrator    stable      17

## Log output
```
# juju status
Model       Controller          Cloud/Region        Version  SLA          Timestamp
postgresql  microk8s-localhost  microk8s/localhost  3.1.8    unsupported  22:50:29Z

App              Version  Status   Scale  Charm            Channel    Rev  Address         Exposed  Message
data-integrator           active       1  data-integrator  stable      27  10.152.183.20   no
pgbouncer-k8s    1.21.0   active       3  pgbouncer-k8s    1/stable   103  10.152.183.206  no
postgresql-k8s   14.10    waiting      3  postgresql-k8s   14/stable  193  10.152.183.106  no       installing agent
s3-integrator             active       1  s3-integrator    stable      17  10.152.183.112  no

Unit                Workload  Agent  Address       Ports  Message
data-integrator/0*  active    idle   10.1.177.47
pgbouncer-k8s/0     active    idle   10.1.1.10
pgbouncer-k8s/1*    active    idle   10.1.192.235
pgbouncer-k8s/2     active    idle   10.1.177.39
postgresql-k8s/0    active    idle   10.1.177.57
postgresql-k8s/1*   error     idle   10.1.1.53            hook failed: "s3-parameters-relation-changed"
postgresql-k8s/2    active    idle   10.1.192.201
s3-integrator/0*    active    idle   10.1.177.40
```

If I did not previously created the bucket -> Error
```
unit-postgresql-k8s-1: 22:26:58 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-1: 22:26:58 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:27:21 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:28:14 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:29:25 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:30:17 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:31:24 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:31:58 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:31:59 WARNING unit.postgresql-k8s/1.juju-log s3-parameters:9: Bucket backups-bucket doesn't exist or you don't have access to it.
unit-postgresql-k8s-1: 22:31:59 ERROR unit.postgresql-k8s/1.juju-log s3-parameters:9: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 1556, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/s3.py", line 745, in _on_relation_changed
    getattr(self.on, "credentials_changed").emit(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 396, in _on_s3_credential_changed
    self._create_bucket_if_not_exists()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 193, in _create_bucket_if_not_exists
    bucket.create(CreateBucketConfiguration={"LocationConstraint": region})
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/boto3/resources/factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/client.py", line 962, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/client.py", line 1036, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter CreateBucketConfiguration.LocationConstraint, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
unit-postgresql-k8s-1: 22:32:00 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-1: 22:32:00 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:32:14 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:33:19 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
```

If I created the bucket, and updated charm config value for an existing bucket -> Error 

```
unit-postgresql-k8s-1: 22:46:40 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-1: 22:46:40 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:47:00 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:47:01 INFO unit.postgresql-k8s/1.juju-log s3-parameters:9: Bucket postgresql exists.
unit-postgresql-k8s-1: 22:47:01 ERROR unit.postgresql-k8s/1.juju-log s3-parameters:9: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 1556, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/data_platform_libs/v0/s3.py", line 745, in _on_relation_changed
    getattr(self.on, "credentials_changed").emit(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 401, in _on_s3_credential_changed
    can_use_s3_repository, validation_message = self.can_use_s3_repository()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/backups.py", line 130, in can_use_s3_repository
    system_identifier_from_stanza = str(stanza.get("db")[0]["system-id"])
IndexError: list index out of range
unit-postgresql-k8s-1: 22:47:01 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-1: 22:47:01 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:47:03 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:47:41 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-postgresql-k8s-1: 22:47:42 INFO unit.postgresql-k8s/1.juju-log s3-parameters:9: Bucket postgresql exists.
unit-postgresql-k8s-1: 22:47:42 ERROR unit.postgresql-k8s/1.juju-log s3-parameters:9: Uncaught exception while in charm code:
```

## Aditional information
Removing the relation after it is on error state leaves unit anyway in error state

**Comment by dragomirp** [comment]
Hi, @gustavosr98, can you try enabling TLS on the bucket endpoint? Pgbackrest requires encrypted endpoint to work with S3.

**Comment by gustavosr98** [comment]
I can enable on the server side
Now, how should I pass the server CA certificates for the PostgreSQL charm to trust this certificate?

I do not find an option for it here
https://charmhub.io/postgresql-k8s/configuration

Would it be on the s3-integrator charm here?
https://charmhub.io/s3-integrator/configuration#tls-ca-chain

I will test with this and see

**Comment by taurus-forever** [comment]
Dear @gustavosr98 ,

Yes, you should drop your CA into [s3-integrator](https://charmhub.io/s3-integrator/configuration#tls-ca-chain).
Please share your test results.

Thank you!

**Comment by marceloneppel** [comment]
Hi, @gustavosr98!

The revision 418 from the `14/edge` channel contains the fix for this issue.

With that revision, PostgreSQL will use the TLS CA chain (`tls-ca-chain` config option) provided through the S3 Integrator charm.

```sh
juju config s3-integrator \
    endpoint="https://radosgw.mycompany.fqdn" \
    bucket="backups-bucket" \
    path="/postgresql" \
    region="" \
    s3-api-version="" \
    s3-uri-style="path" \
    tls-ca-chain="$(base64 -w0 /path-to-your-server-ca-file)"
```

I also updated both https://discourse.charmhub.io/t/charmed-postgresql-k8s-how-to-configure-s3-for-radosgw/10316 and https://discourse.charmhub.io/t/charmed-postgresql-how-to-configure-s3-for-radosgw/10313 with that configuration field. Those are the topics that will be published in the official documentation on Charmhub (one of them is the one that you used earlier: https://charmhub.io/postgresql-k8s/docs/h-configure-s3-radosgw).
