### ISSUE TITLE
Conflict when co-existing with pgbouncer charm

### ISSUE THREAD

**Issue by gustavosr98** [canonical/postgresql-operator#636]
## Steps to reproduce
Install pgbouncer charm on a machine
Then try to install postgresql charm on the same machine

## Expected behavior
They should be able to co-exist on the same machine

## Actual behavior
Stuck at install hook

## Versions
pgbouncer        1/stable       396
postgresql       14/stable      468
Juju 3.5.3

## Log output
```
# juju status
[..]
data-integrator/0   blocked   idle   0        192.168.0.188             Please relate the data-integrator with the desired product
  pgbouncer/4       blocked   idle            192.168.0.188   6432/tcp  waiting for backend database relation to initialise
data-integrator/1*  blocked   idle   1        192.168.0.150             Please relate the data-integrator with the desired product
  pgbouncer/1       blocked   idle            192.168.0.150   6432/tcp  waiting for backend database relation to initialise
data-integrator/2   blocked   idle   2        192.168.0.10              Please relate the data-integrator with the desired product
  pgbouncer/5       blocked   idle            192.168.0.10    6432/tcp  waiting for backend database relation to initialise
[..]
postgresql/0        error     idle   0        192.168.0.188             hook failed: "install"
postgresql/1*       error     idle   1        192.168.0.150             hook failed: "install"
postgresql/2        error     idle   2        192.168.0.10              hook failed: "install"
```

```bash
# Logs
2024-10-02 00:33:22 WARNING unit.postgresql/0.install logger.go:60 - Setup manual alias "psql" => "psql" for snap "charmed-postgresql" (cannot enable alias "psql" for "charmed-postgresql", already enabled for "charmed-pgbouncer")
2024-10-02 00:33:23 ERROR unit.postgresql/0.juju-log server.go:325 Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 441, in alias
    subprocess.check_output(args, universal_newlines=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'alias', 'charmed-postgresql.psql', 'psql']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1866, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 553, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 518, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name, self._juju_context)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 139, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 347, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 885, in _on_install
    postgres_snap.alias("psql")
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/operator_libs_linux/v2/snap.py", line 443, in alias
    raise SnapError(
charms.operator_libs_linux.v2.snap.SnapError: Snap: 'charmed-postgresql'; command ['snap', 'alias', 'charmed-postgresql.psql', 'psql'] failed
 with output = ''
2024-10-02 00:33:23 ERROR juju.worker.uniter.operation runhook.go:180 hook "install" (via hook dispatching script: dispatch) failed: exit sta
tus 1
2024-10-02 00:33:23 INFO juju.worker.uniter resolver.go:180 awaiting error resolution for "install" hook
```

**Comment by dragomirp** [comment]
Hi, @gustavosr98, I think the issue is that the Postgresql charm doesn't ignore the alias errors. Can you try the other way around, install Postgresql charm first, wait it to install and then install Pgbouncer on the same machine.

**Comment by dragomirp** [comment]
Hi, latest `14/edge` (revs. 484, 485) should now ignore the duplicate alias.
