### ISSUE TITLE
Second pg cluster in error state after trying to migrate restore from first pg cluster backup

### ISSUE THREAD

**Issue by gustavosr98** [canonical/postgresql-operator#99]
### Bug Description
Second pg cluster got in error state following docs on [how to migrate cluster via restore](https://github.com/canonical/postgresql-operator/blob/main/docs/how-to/h-migrate-cluster-via-restore.md)
 
### To Reproduce

Deploy one postgresql application (pg-b) 
Create two backups

```
$ juju run-action pg-b/0 --wait list-backups       
unit-pg-b-0:
  UnitId: pg-b/0
  id: "63"
  results:
    backups: |-
      backup-id             | backup-type  | backup-status
      ----------------------------------------------------
      2023-03-31T15:30:12Z  | physical     | finished
      2023-03-31T20:21:30Z  | physical     | finished
```

Retrieve operator, replication and rewind credentials from pg-b

Deploy a second postgresql application (pg-d)
Set three credentials from pg-b to pg-d
Relate to existing s3-integrator
List existing backups on the second pg application

```
$ juju run-action pg-d/0 list-backups --wait
$ juju show-action-output 55                                                     
UnitId: pg-d/0
id: "55"
results:
  backups: |-
    backup-id             | backup-type  | backup-status
    ----------------------------------------------------
    2023-03-31T15:30:12Z  | physical     | finished
    2023-03-31T20:21:30Z  | physical     | finished
status: completed
timing:
  completed: 2023-03-31 20:42:45 +0000 UTC
  enqueued: 2023-03-31 20:42:38 +0000 UTC
  started: 2023-03-31 20:42:42 +0000 UTC
```

Try to migrate on second pg application (pg-d) using restore from the first backup of the first application (pg-b)
```
$ juju run-action pg-d/0 --wait restore backup-id=2023-03-31T15:30:12Z --wait
$ juju show-action-output 57
UnitId: pg-d/0
id: "57"
results:
  restore-status: restore started
status: completed
timing:
  completed: 2023-03-31 20:44:32 +0000 UTC
  enqueued: 2023-03-31 20:43:22 +0000 UTC
  started: 2023-03-31 20:43:24 +0000 UTC
```

### Environment
juju: 2.9.42 (Client and Controller)
juju cloud substrate: LXD

postgresql charm: latest/edge (rev 281)
s3-integrator charm: latest/edge (rev 8)

s3 provider: AWS S3

### Relevant log output

```
$ juju status                   
Model      Controller  Cloud/Region         Version  SLA          Timestamp
pg-backup  lxd         localhost/localhost  2.9.42   unsupported  16:53:59-05:00

App            Version  Status  Scale  Charm          Channel  Rev  Exposed  Message
pg-b                    active      1  postgresql     edge     281  no       Primary
pg-d                    error       1  postgresql     edge     281  no       hook failed: "update-status"
s3-integrator           active      1  s3-integrator  edge       8  no       

Unit              Workload  Agent  Machine  Public address  Ports  Message
pg-b/0*           active    idle   0        10.46.90.84            Primary
pg-d/0*           error     idle   5        10.46.90.153           hook failed: "update-status"
s3-integrator/0*  active    idle   1        10.46.90.246           

Machine  State    Address       Inst id        Series  AZ  Message
0        started  10.46.90.84   juju-46d4f8-0  jammy       Running
1        started  10.46.90.246  juju-46d4f8-1  jammy       Running
5        started  10.46.90.153  juju-46d4f8-5  jammy       Running
```

```
$ juju show-status-log pg-d/0 --days 1
Time                        Type       Status       Message
31 Mar 2023 15:17:36-05:00  juju-unit  allocating   
31 Mar 2023 15:17:36-05:00  workload   waiting      waiting for machine
31 Mar 2023 15:23:24-05:00  workload   waiting      installing agent
31 Mar 2023 15:23:25-05:00  workload   waiting      agent initializing
31 Mar 2023 15:23:31-05:00  juju-unit  executing    running pgdata-storage-attached hook
31 Mar 2023 15:23:32-05:00  workload   maintenance  installing charm software
31 Mar 2023 15:23:32-05:00  juju-unit  executing    running install hook
31 Mar 2023 15:23:33-05:00  workload   maintenance  installing PostgreSQL
31 Mar 2023 15:26:35-05:00  workload   waiting      waiting to start PostgreSQL
31 Mar 2023 15:26:36-05:00  juju-unit  executing    running restart-relation-created hook
31 Mar 2023 15:26:37-05:00  juju-unit  executing    running database-peers-relation-created hook
31 Mar 2023 15:26:37-05:00  juju-unit  executing    running leader-elected hook
31 Mar 2023 15:27:39-05:00  juju-unit  executing    running config-changed hook
31 Mar 2023 15:27:39-05:00  juju-unit  executing    running start hook
31 Mar 2023 15:27:45-05:00  juju-unit  executing    running database-peers-relation-changed hook
31 Mar 2023 15:27:47-05:00  workload   active       
31 Mar 2023 15:27:47-05:00  juju-unit  idle         
31 Mar 2023 15:35:05-05:00  workload   active       Primary
31 Mar 2023 15:37:34-05:00  juju-unit  executing    running action set-password
31 Mar 2023 15:37:34-05:00  juju-unit  idle         
31 Mar 2023 15:37:35-05:00  juju-unit  executing    running database-peers-relation-changed hook
31 Mar 2023 15:37:36-05:00  juju-unit  idle         
31 Mar 2023 15:37:54-05:00  juju-unit  executing    running action set-password
31 Mar 2023 15:37:55-05:00  juju-unit  idle         
31 Mar 2023 15:37:55-05:00  juju-unit  executing    running database-peers-relation-changed hook
31 Mar 2023 15:37:56-05:00  workload   active       
31 Mar 2023 15:37:57-05:00  juju-unit  idle         
31 Mar 2023 15:39:17-05:00  workload   active       Primary
31 Mar 2023 15:40:16-05:00  juju-unit  executing    running action set-password
31 Mar 2023 15:40:17-05:00  juju-unit  idle         
31 Mar 2023 15:40:17-05:00  juju-unit  executing    running database-peers-relation-changed hook
31 Mar 2023 15:40:18-05:00  workload   active       
31 Mar 2023 15:40:19-05:00  juju-unit  idle         
31 Mar 2023 15:41:57-05:00  juju-unit  executing    running s3-parameters-relation-created hook
31 Mar 2023 15:41:58-05:00  juju-unit  executing    running s3-parameters-relation-joined hook for s3-integrator/0
31 Mar 2023 15:41:58-05:00  juju-unit  executing    running s3-parameters-relation-changed hook for s3-integrator/0
31 Mar 2023 15:41:59-05:00  juju-unit  executing    running s3-parameters-relation-changed hook
31 Mar 2023 15:42:00-05:00  workload   maintenance  initialising stanza
31 Mar 2023 15:42:12-05:00  workload   active       
31 Mar 2023 15:42:13-05:00  juju-unit  idle         
31 Mar 2023 15:42:41-05:00  juju-unit  executing    running action list-backups
31 Mar 2023 15:42:45-05:00  juju-unit  idle         
31 Mar 2023 15:43:23-05:00  juju-unit  executing    running action restore
31 Mar 2023 15:43:28-05:00  workload   maintenance  restoring backup
31 Mar 2023 15:44:32-05:00  juju-unit  idle         
31 Mar 2023 15:44:35-05:00  juju-unit  executing    running database-peers-relation-changed hook
31 Mar 2023 15:53:04-05:00  juju-unit  idle         
31 Mar 2023 16:16:09-05:00  juju-unit  error        hook failed: "update-status"
31 Mar 2023 16:25:03-05:00  juju-unit  idle         
31 Mar 2023 16:35:08-05:00  juju-unit  error        hook failed: "update-status"
31 Mar 2023 16:55:39-05:00  juju-unit  executing    running action list-backups
31 Mar 2023 16:59:09-05:00  juju-unit  error        hook failed: "update-status"
31 Mar 2023 17:06:43-05:00  workload   waiting      awaiting for member to start
```

```
$ juju ssh pg-d/0 "sudo less /var/log/juju/unit-pg-d-0.log"
[..]
2023-03-31 20:27:39 INFO juju.worker.uniter.operation runhook.go:159 ran "config-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:27:39 INFO juju.worker.uniter resolver.go:159 found queued "start" hook
2023-03-31 20:27:40 INFO unit.pg-d/0.juju-log server.go:316 Running legacy hooks/start.
2023-03-31 20:27:45 INFO juju.worker.uniter.operation runhook.go:159 ran "start" hook (via hook dispatching script: dispatch)
2023-03-31 20:27:45 INFO unit.pg-d/0.juju-log server.go:316 database-peers:17: Starting cluster topology observer process
2023-03-31 20:27:45 INFO unit.pg-d/0.juju-log server.go:316 database-peers:17: Started cluster topology observer process with PID 15967
2023-03-31 20:27:46 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:27:47 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:29:12 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 20:29:12 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 20:35:05 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 20:35:05 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 20:37:36 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:37:57 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:39:17 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 20:39:17 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 20:40:18 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: 
dispatch)
2023-03-31 20:41:57 INFO juju.worker.uniter.operation runhook.go:159 ran "s3-parameters-relation-created" hook (via hook dispatching script: dispatch)
2023-03-31 20:41:58 INFO juju.worker.uniter.operation runhook.go:159 ran "s3-parameters-relation-joined" hook (via hook dispatching script: dispatch)
2023-03-31 20:41:59 WARNING unit.pg-d/0.juju-log server.go:316 s3-parameters:18: Some mandatory fields: ['access-key', 'secret-key'] are not present, do not emit credential change event!
2023-03-31 20:41:59 INFO juju.worker.uniter.operation runhook.go:159 ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:42:12 INFO juju.worker.uniter.operation runhook.go:159 ran "s3-parameters-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:43:24 INFO unit.pg-d/0.juju-log server.go:316 Checking if cluster is in blocked state
2023-03-31 20:43:24 INFO unit.pg-d/0.juju-log server.go:316 Checking that the cluster does not have more than one unit
2023-03-31 20:43:24 INFO unit.pg-d/0.juju-log server.go:316 A restore with backup-id 2023-03-31T15:30:12Z has been requested on unit
2023-03-31 20:43:24 INFO unit.pg-d/0.juju-log server.go:316 Validating provided backup-id
2023-03-31 20:43:28 INFO unit.pg-d/0.juju-log server.go:316 Stopping database service
2023-03-31 20:43:30 INFO unit.pg-d/0.juju-log server.go:316 Removing the contents of the data directory
2023-03-31 20:43:30 INFO unit.pg-d/0.juju-log server.go:316 Configuring Patroni to restore the backup
2023-03-31 20:44:31 INFO unit.pg-d/0.juju-log server.go:316 Configuring Patroni to restore the backup
2023-03-31 20:44:31 INFO unit.pg-d/0.juju-log server.go:316 Removing previous cluster information
2023-03-31 20:45:41 INFO unit.pg-d/0.juju-log server.go:316 database-peers:17: Deferring reconfigure: couldn't retrieve current cluster members
2023-03-31 20:47:21 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
2023-03-31 20:48:23 ERROR unit.pg-d/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

2023-03-31 20:49:42 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 20:49:42 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 20:51:17 ERROR unit.pg-d/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

2023-03-31 20:53:04 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 20:53:04 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 20:56:03 INFO unit.pg-d/0.juju-log server.go:316 Deferring reconfigure: couldn't retrieve current cluster members
2023-03-31 20:57:20 ERROR unit.pg-d/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

2023-03-31 20:59:15 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 20:59:16 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 21:00:31 INFO unit.pg-d/0.juju-log server.go:316 Deferring reconfigure: couldn't retrieve current cluster members
2023-03-31 21:01:57 ERROR unit.pg-d/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

2023-03-31 21:03:10 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 21:03:11 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 21:05:29 INFO unit.pg-d/0.juju-log server.go:316 Deferring reconfigure: couldn't retrieve current cluster members
2023-03-31 21:08:36 ERROR unit.pg-d/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

2023-03-31 21:10:25 WARNING unit.pg-d/0.juju-log server.go:316 No relation: certificates
2023-03-31 21:10:25 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 21:11:32 INFO unit.pg-d/0.juju-log server.go:316 Deferring reconfigure: couldn't retrieve current cluster members
2023-03-31 21:14:08 ERROR unit.pg-d/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution
2023-03-31 21:16:09 ERROR unit.pg-d/0.juju-log server.go:316 Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd69f3b8fd0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.46.90.153', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd69f3b8fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/src/cluster.py", line 213, in get_member_status
    cluster_status = requests.get(
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.46.90.153', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd69f3b8fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/./src/charm.py", line 1032, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/./src/charm.py", line 831, in _on_update_status
    if "failed" in self._patroni.get_member_status(self._member_name):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/src/cluster.py", line 210, in get_member_status
    for attempt in Retrying(stop=stop_after_attempt(2 * len(self.peers_ips) + 1)):
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-pg-d-0/charm/venv/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fd69f3b9240 state=finished raised ConnectionError>]
[..]
```

> Note: Error log about host name can also be seen in first postgresql application (pg-b) when doing a **successful** restore from a backup created by the same application.
```
2023-03-31 19:39:49 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 19:43:46 INFO unit.pg-b/0.juju-log server.go:316 Checking if cluster is in blocked state
2023-03-31 19:43:46 INFO unit.pg-b/0.juju-log server.go:316 Checking that the cluster does not have more than one unit
2023-03-31 19:43:46 INFO unit.pg-b/0.juju-log server.go:316 A restore with backup-id 2023-03-31T15:30:12Z has been requested on unit
2023-03-31 19:43:46 INFO unit.pg-b/0.juju-log server.go:316 Validating provided backup-id
2023-03-31 19:43:56 INFO unit.pg-b/0.juju-log server.go:316 Stopping database service
2023-03-31 19:44:02 INFO unit.pg-b/0.juju-log server.go:316 Removing the contents of the data directory
2023-03-31 19:44:02 INFO unit.pg-b/0.juju-log server.go:316 Configuring Patroni to restore the backup
2023-03-31 19:45:02 INFO unit.pg-b/0.juju-log server.go:316 Configuring Patroni to restore the backup
2023-03-31 19:45:03 INFO unit.pg-b/0.juju-log server.go:316 Removing previous cluster information
2023-03-31 19:45:06 INFO juju.worker.uniter.operation runhook.go:159 ran "database-peers-relation-changed" hook (via hook dispatching script: 
dispatch)
2023-03-31 19:46:41 ERROR unit.pg-b/0.juju-log server.go:316 Failed to list PostgreSQL database users: could not translate host name "None" to
 address: Temporary failure in name resolution

2023-03-31 19:47:43 WARNING unit.pg-b/0.juju-log server.go:316 No relation: certificates
2023-03-31 19:47:44 INFO juju.worker.uniter.operation runhook.go:159 ran "update-status" hook (via hook dispatching script: dispatch)
2023-03-31 19:51:22 WARNING unit.pg-b/0.juju-log server.go:316 No relation: certificates
```

**Comment by marceloneppel** [comment]
Hi @gustavosr98!

We'll be working to fix this on the next pulse.

**Comment by marceloneppel** [comment]
https://github.com/canonical/postgresql-operator/pull/120 should fix this. It's currently in review.

**Comment by marceloneppel** [comment]
Solved by https://github.com/canonical/postgresql-operator/pull/120.
